name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint & Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.13"
          python-version: ${{ matrix.python-version }}

      - name: Lint check Python:${{ matrix.python-version }}
        run: uv run ruff check

      - name: Tests Python:${{ matrix.python-version }}
        run: uv run pytest tests --cov --cov-report=xml --cov-report=term

      # TODO: Setup CodeCov
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     slug: sapientinc/HRM